#!/usr/bin/env bash

while read file
do
	fullpath="$(pwd)/$file"
	case "$1" in
	"r")
		new_name=$(rofi -m -4 -dmenu -l 0 -p "new name")
		mv "$fullpath" "$(pwd)/$new_name" ;;
	"d")
		[[ $(rofi -m -4 -dmenu -l 0 -p "delete[y/n]") == "y" ]] && rm "$file" && notify-send -i "$fullpath" "Deleted" ;;
	esac
done
