#!/bin/bash

DIR="$1"
source="$2"
tracklist="$3"
DELIM="$4"
EXT="$5"

[[ ! -d "$DIR" ]] && printf "[ERROR]: Argument \$1 should be a directory. Exiting...\n" && exit 1
[[ ! -e "$source" ]] && printf "[ERROR]: Argument \$2 should be audio source but was not found. Exiting...\n" && exit 1
[[ ! -e "$tracklist" ]] && printf "[ERROR]: Argument \$3 should be tracklist but was not found. Exiting...\n" && exit 1
[[ -z "$DELIM" || -z "$EXT" ]] && printf "[ERROR]: Arguments \$4 and \$5 should be DELIM and EXT but one or more is empty. Exiting...\n" && exit 1

num_tracks="$(cat "$tracklist" | wc -l)"
tracks_dir="$DIR/tracks"

# [[ -d $dir && $(ls $dir | wc -l) -gt 0 ]] && printf "[ERROR]: [$tracks_dir] directory already exists and is not empty. Exiting...\n" && exit 1

i=1
cat "$tracklist" | while read l; do
    title="$(echo "$l" | awk -F "$DELIM" '{print $1}' | sed 's/ /_/g').$EXT"
    ts="$(echo "$l" | awk -F "$DELIM" '{print $2}')"
    artist="$(echo "$l" | awk -F "$DELIM" '{print $3}')"

    [[ -z "$artist" ]] && artist="Unknown"

    start="$(echo $ts | awk -F "-" '{print $1}')"
    end="$(echo $ts | awk -F "-" '{print $2}')"

    mkdir -vp "$tracks_dir"

    # Track already exists and has a size greater than 0
    [[ -f "$tracks_dir/$title" && $(du "$tracks_dir/$title" | awk '{print $1}') -gt 0 ]] && i=$((i+1)) && continue

    printf "[INFO]: $i/$num_tracks. Processing %s -> %s by (%s)...\n" "$(basename "$source")" "$title" "$artist"

    ffmpeg \
	-y \
	-nostdin \
	-hide_banner -loglevel error \
	-ss "$start" -to "$end" \
	-i "$source" \
	-c:v copy \
	-metadata track="$i/$num_tracks" \
	-metadata artist="$artist" \
	"$tracks_dir/$title"

    i=$((i+1))
done
