#!/bin/sh

# This script works as a wrapper to the 'du' utility
# Most of everything done by it can be instead achieved by using 'du' directly
# Some QoL features include:
# - sort results based on size

# Defaults
DIR="$1"
DEPTH="1"
while getopts ":D:d:" o; do
    case "$o" in
	D) DEPTH="$OPTARG" ;;
	d) DIR="$OPTARG" ;;
	*) echo "Invalid usage of $(basename $0)" && exit 1 ;;
    esac
done

du -abd "$DEPTH" $DIR 2> /dev/null | sort -n | numfmt --to iec
