#!/bin/sh

if [ -n "$(pacmd list-sinks | grep 'Navi')" ]; then
    NAVI_CARD=$(pacmd list-cards | grep -B 15 'product.name = "Navi' | awk 'NR==1 {print $2}')
    pacmd set-card-profile $NAVI_CARD off
fi

pacmd set-default-sink $(pacmd list-sinks | sed -En 's/^ +index: ([0-9]+).*/\1/p')
[ -z $(pactl get-default-sink | grep "HyperX") ] && echo "Speakers" || echo "Headphones"
